### ISSUE TITLE
dancing bug

### ISSUE THREAD

**Issue by SadBeYou** [Silenci0/SMAC#1]
i was doing the Conga and hit f2 for contracts i got this 
https://imgur.com/a/6n4ZzZJ
nice little bug

**Comment by Silenci0** [comment]
Thank you for letting me know about this. I'm assuming you are using the smac_eyetest.smx module on the server, which currently doesn't work in TF2 or CS:GO, though I only heard this was for alt-tabbing and not the Conga taunt (past versions of this module had issues with the Conga taunt). 

I will keep this in mind when attempting to fix this bug with eye test, but for now, you may want to disable smac_eyetest.smx on your server or at least ensure that the module is not set to automatically ban upon detection.

**Comment by SadBeYou** [comment]
please fix it for tf2

**Comment by Silenci0** [comment]
So, as an update, I was looking into this issue recently and I found that I could replicate it, but only once. It appears that its a combination of using a taunt like the conga taunt in addition to pressing F2 for opening the contract menu for the first time after starting the game while taunting, or at least thats what it I experienced while attempting to replicate this issue in the eyetest module.

It seems that subsequent attempts to replicate this issue after the first attempt wouldn't work by repeating these steps. It also would not work if I did not taunt and opened the contract menu, then did the taunt and opened the contract menu. I believe, based on what I've seen so far, is that this issue occurs due to loading the contract menu for the first time (either on the server or since starting the game client itself) while taunting. The game attempts to load it before it recognizes what you are doing and tries to stop you. For a split second, you actually load the menu but are kicked out, with subsequent attempts being blocked by the game to access this menu while taunting. Since the error is very similar to errors found when alt-tabbing, it seems it could be related to that.

While this can be replicated, it does not seem to occur after the first time or repeatedly, so it will not immediately ban anyone for doing it once. Considering there are problems with eyetest already, you might want to disable automatic bans for this module and try setting compatibility mode to 1 for now.

**Comment by Silenci0** [comment]
This issue has been resolved in the latest 0.8.6.4 update. It was the same issue as the alt-tabbing issue that flagged users for using the same usercmds via tickcount. After fixing that, this bug does not come up anymore in TF2 (and possibly CS:GO).

I would still advise anyone using this module to keep the ban feature off and using compatibility mode for now, but I think the dancing bug should be resolved now. Thanks for the report, closing issue.
