### ISSUE TITLE
Aimbot Detector starts counting from 2, and therefore bans earlier as should

### ISSUE THREAD

**Issue by borzaka** [Silenci0/SMAC#12]
I have set `smac_aimbot_ban` to `"6"`, but it bans after the 5th detection, because detection counter starts at 2:

```
L 09/24/2019 - 21:14:43: [smac_aimbot.smx | 0.8.6.5] RETARDED DOG *bark* (ID: STEAM_1:0:462592946 | IP: 185.236.42.73) is suspected of using an aimbot. (Detection #2 | Deviation: 99° | Weapon: weapon_usp_silencer)
	Map: de_mirage | Origin: 77 -1528 -175 | Angles: 0 -1 0 | Weapon: weapon_usp_silencer | Team: 3 | Latency: 76ms
L 09/24/2019 - 21:14:47: [smac_aimbot.smx | 0.8.6.5] RETARDED DOG *bark* (ID: STEAM_1:0:462592946 | IP: 185.236.42.73) is suspected of using an aimbot. (Detection #3 | Deviation: 100° | Weapon: weapon_usp_silencer)
	Map: de_mirage | Origin: -114 -2023 -167 | Angles: -0 -101 0 | Weapon: weapon_usp_silencer | Team: 3 | Latency: 75ms
L 09/24/2019 - 21:15:01: [smac_aimbot.smx | 0.8.6.5] RETARDED DOG *bark* (ID: STEAM_1:0:462592946 | IP: 185.236.42.73) is suspected of using an aimbot. (Detection #4 | Deviation: 100° | Weapon: weapon_usp_silencer)
	Map: de_mirage | Origin: -1353 -970 -167 | Angles: -4 23 0 | Weapon: weapon_usp_silencer | Team: 3 | Latency: 73ms
L 09/24/2019 - 21:15:03: [smac_aimbot.smx | 0.8.6.5] RETARDED DOG *bark* (ID: STEAM_1:0:462592946 | IP: 185.236.42.73) is suspected of using an aimbot. (Detection #5 | Deviation: 99° | Weapon: weapon_usp_silencer)
	Map: de_mirage | Origin: -1236 -1209 -167 | Angles: -0 -38 0 | Weapon: weapon_usp_silencer | Team: 3 | Latency: 75ms
L 09/24/2019 - 21:15:07: [smac_aimbot.smx | 0.8.6.5] RETARDED DOG *bark* (ID: STEAM_1:0:462592946 | IP: 185.236.42.73) is suspected of using an aimbot. (Detection #6 | Deviation: 100° | Weapon: weapon_usp_silencer)
	Map: de_mirage | Origin: -662 -1306 -167 | Angles: 8 81 0 | Weapon: weapon_usp_silencer | Team: 3 | Latency: 74ms
L 09/24/2019 - 21:15:07: [smac_aimbot.smx | 0.8.6.5] RETARDED DOG *bark* (ID: STEAM_1:0:462592946 | IP: 185.236.42.73) was banned for using an aimbot.
	Map: de_mirage | Origin: -662 -1306 -167 | Angles: 8 81 0 | Weapon: weapon_usp_silencer | Team: 3 | Latency: 74ms
```

There was no `Detection #1`

I know, that it [ignores the first detection](https://github.com/Silenci0/SMAC/wiki/Aimbot-Detector), which is good, but that ignored detection shouldn't count as part of further detections.

**Comment by Silenci0** [comment]
Hello borzaka,

While I can understand the rationale from a logging perspective, I must disagree with not counting the first detection. 

The module is banning on the 6th detection as it is supposed to, but the initial detection (which is Detection 1) is ignored via logging simply due to the potential of it being a false positive, which can spam the logs and potentially confuse admins. If it is a false positive, and not subsequent detections are made, logging the first detection would not be useful. 

However, the reason this detection is still counted is due to the potential that it is actually someone using an aimbot, which will most likely show up with subsequent detections after the initial detection is made, which it will then log said detections as the potential of a player using an aimbot is much higher. The module will then log all subsequent detections after Detection 1, which is why it starts with Detection 2 in the logs

Making it so that it does not count the initial detection could make it easier to circumvent the module in general and dodge detections, which would make the module less useful. It wouldn't make sense to add an additional detection that would end up ignored before detections could begin for the same reason as well.

Thank you,

Silence

**Comment by borzaka** [comment]
So, if later there are more detections for the same user, the first detection will be counted as well.

Thank you for the detailed answer to help me understand!
