### ISSUE TITLE
[BUG] Update sourcebans++ native

### ISSUE THREAD

**Issue by Drmohammad11** [Silenci0/SMAC#13]
hi friend!!
please update smac for sourcebans++ !!
why i can not pull requests ??

thank you

**Comment by borzaka** [comment]
I'am using SMAC with SourceBans++ and I have already two permanent bans triggered by SMAC. And they are showing up correctly at the bans page.
I'am using the latest versions and compiled booth myself with 1.9 SourceMod.

**Comment by Drmohammad11** [comment]
check this:
`#define SOURCEBANS_AVAILABLE()	(GetFeatureStatus(FeatureType_Native, "SBBanPlayer") == FeatureStatus_Available)`

**Comment by Silenci0** [comment]
Ah okay, I see what you are saying. There is a new native for Sourcebans++ and the old native is depreciated. I'll get to updating this as soon as possible to add support for the new native.

As far as pull requests, you should be able to do them as another person has already done so with this repository for Chinese translations. I would be more than happy to accept pull requests/contributions to SMAC, after review of the code of course, as updates/fixes would be much easier if more than myself was working on this.

Regardless, I'll get to work on updating this for all the affected modules and I'll see about trying to push out an update as soon as possible to support Sourcebans++, thank you for making me aware of the issue!

**Comment by Silenci0** [comment]
Hello,

I have uploaded an update for SMAC to version 0.8.6.6 which includes support for the new Sourcebans++ native. I made sure that the check in Native_Ban would check for the new Sourcebans++ native first, then the depreciated native if it was not found next, with the default ban/kick set as last in the case Sourcebans is not present. I tested that the changes would compile and that the plugins would load on the server and it seems like it is working, but if it does not work, please let me know.

Also, I just noticed that @Drmohammad11 had made a pull request earlier today (https://github.com/Silenci0/SMAC/pull/14), but I did not see it prior to uploading my changes. I'm very sorry that I did not notice this. The changes made are pretty much the same as yours except the define is named differently and the order of the if statement in Native_Ban was set so that the new Sourcebans++ native would be checked first since, if left the other way around, it would continue to use the depreciated native as it still exists. 

Regardless, thank you for making the pull request and, again, I am very sorry that I did not see it earlier. I will close out the pull request as unaccepted, but know that I would have accepted it had I saw it earlier. Thank you for your work!

I will close this issue in a few days assuming that the plugins are working correctly. Please let me know if there are any further issues.

Thank you,

Silence

**Comment by Drmohammad11** [comment]
i tested new update and this worked for sourcebans++. thank you
