### ISSUE TITLE
maybe use updater?

### ISSUE THREAD

**Issue by Sufferiney** [Silenci0/SMAC#22]
https://forums.alliedmods.net/showthread.php?t=169095 why not?

**Comment by Silenci0** [comment]
There are a number of reasons, some of it stemming from a few years ago when I created the repo. At the time, I made an unofficial fork to fix issues with ZPS for a friend which required the updater feature to be removed since it would attempt to upgrade the plugins to the official version. When I made the modifications public sometime later for others to use, I did not realize at the time this would become a popular version of SMAC. 

The other reason, at least at present, is due to setting up everything for updating and the current development state of SMAC in general. Currently, I'm maintaining the plugins and attempting to make fixes where I can, but my testing is only done on Windows and in TF2 and ZPS so I cannot guarantee that my fixes will work with other games. Because of this, I'd rather not force updates on people as it could potentially cause issues for them. I also think its better to plan for an upgrade rather than to have one forced upon someone since it allows the server owners the flexibility to test the updates themselves or to move at their own pace without having to rush to fix issues that they are unaware of as a result of an automatic update. On top of this, I do not really have any domains/URLs setup for this and smac.sx is setup to redirect to the Github repo at this time.

With all that said, updater is a great tool that should be used where it can, but at the moment I think it might be wise for SMAC to not use it at this time. It is a consideration that I think will be added back at a later date, but just not right now.

**Comment by Sufferiney** [comment]
maybe add funcsion sman_no_update=1?

**Comment by Silenci0** [comment]
It will happen later, just not right now.

**Comment by Sufferiney** [comment]
thx
