### ISSUE TITLE
smac crashing when admin menu is open

### ISSUE THREAD

**Issue by Ayrton09** [Silenci0/SMAC#24]
hello silenci0 how are you?, testing the latest version i found a weird bug, when i open the admin menu the server goes crash lol, removing the smac_rcon didnt help but removing all the new smac plugins fix the problem.

**Comment by Silenci0** [comment]
Could you list the SMAC plugins you were using on your server as well as the SM version and game? I'm assuming the game is CS:GO, but I want to make sure of that first.

**Comment by Ayrton09** [comment]
SourceMod Version: 1.10.0.6455
 Game: csgo

at the first try i used these but now i remove it to avoid crashing.

![Anotación 2019-11-19 074638](https://user-images.githubusercontent.com/47057206/69140174-c129ab00-0aa0-11ea-8075-53495b94d18d.jpg)

**Comment by Silenci0** [comment]
okay got it, I'll take a look at these and see what is causing the issue. I'm thinking this might have to do with the latest CS:GO update as well, but I can't be certain on that. Thanks for the report and I'll respond back to this as soon as possible.

**Comment by caxanga334** [comment]
Install [Accelerator](https://forums.alliedmods.net/showthread.php?t=277703&), this will give us a more precise information about the crash.

**Comment by Ayrton09** [comment]
> Install [Accelerator](https://forums.alliedmods.net/showthread.php?t=277703&), this will give us a more precise information about the crash.

im using it but just now the pag is down 
![Anotación 2019-11-19 090250](https://user-images.githubusercontent.com/47057206/69145008-66e21780-0aab-11ea-9940-5edc064e1cf7.jpg)

**Comment by Silenci0** [comment]
Hi Ayrton,

I was able to replicate this and I think I know why its happening. It wasn't noticed during testing, but when I turned on the welcome message, I did get an error in the error logs blaming the smac module due to referencing a function in the morecolors include, which seemed to crash the server directly after the welcome message was displayed (if I was able to open the menu prior to that, it would work fine until I tried to open it again). So its very likely this is related to a bug with displaying text in chat incorrectly.

Could you look in sourcemod/logs in the file "errors_<date>.log" that were generated between now and when you updated SMAC and see if any smac-related error logs were left behind? If so, could you post them here for me to look? In the meantime, I'll be working on a fix for the bug I ran into and attempt to get it out ASAP.

**Comment by caxanga334** [comment]
@Silenci0 
```
L 11/19/2019 - 13:51:25: [SM] Exception reported: Invalid field "params" for message "CCSUsrMsg_SayText2"
L 11/19/2019 - 13:51:25: [SM] Blaming: smac.smx
L 11/19/2019 - 13:51:25: [SM] Call stack trace:
L 11/19/2019 - 13:51:25: [SM]   [0] Protobuf.SetString
L 11/19/2019 - 13:51:25: [SM]   [1] Line 206, C:\compiler\sm10\include\morecolors.inc::CSendMessage
L 11/19/2019 - 13:51:25: [SM]   [2] Line 48, C:\compiler\sm10\include\morecolors.inc::CPrintToChat
L 11/19/2019 - 13:51:25: [SM]   [3] Line 202, C:\compiler\sm10\smac.sp::Timer_WelcomeMsg
```

[Crash Info](https://crash.limetech.org/va637fve54jb)

**Comment by Silenci0** [comment]
Aside from the CPrintToChat feature, there is the CRemoveTags feature (colors/morecolors has this) for the IRC Mode to consider since that removes the color tags ( {default} {green} etc.) from the buffer message when sending the message to IRC. Though I don't know how many people actually use the IRC mode, I'd rather not remove this unless there is no other choice.

Other than that, I agree on switching to PrintToChat since it would be simple/compatible with everything and we'd have one less include to deal with. I'll attempt to fix up the colors include first and revert back to that for now. I'll have an update out later today.

**Comment by Silenci0** [comment]
Update 0.8.7.1 has been released and addresses this issue. It was tested with CS:GO and no crashes were experienced while testing. Please use the latest release and let me know if it is working for you now @Ayrton09

**Comment by Ayrton09** [comment]
thanks silenci0! testing now i will let you know if something is wrong.

**Comment by Ayrton09** [comment]
fixed thanks! :)
