### ISSUE TITLE
Smac color message

### ISSUE THREAD

**Issue by lunatixxx** [Silenci0/SMAC#26]
Since the last update {green} SMAC {green} in the translation file doesn't work anymore, what should be used now if i want to make it yellow ?

**Comment by caxanga334** [comment]
Colors are disabled due to crash issues with CSGO. If you want to use colors, you need to modify the plugin code.

**Comment by lunatixxx** [comment]
Any change it will come back ? it is disabled too on L4D2.

**Comment by Silenci0** [comment]
The change in the latest release was made due to changing from the old colors include to morecolors which seems to have problems with CS:GO (ie: it causes a crash on the server). I had removed morecolors and the functions causing the crashes since it might have had the same issue with other games aside from CS:GO.

I may bring it back using the old colors include/functions, but only after I test some things first to make sure its safe/compatible, but I won't promise anything. To be honest, it might be better to remove color chat messages in general for maximum compatibility with all games, but I can understand why people would rather have different color messages for these alerts. I will respond back when I've had time to test some things out.

**Comment by Silenci0** [comment]
I have tested this and found that the colors.inc file does work with CS:GO and does not cause any problems/crashes when bringing up the admin menu. Using the {green} color code in the translation file also had the color properly show up in the welcome message used in the chat function. So it should be safe for CS:GO and L4D2 as well. The latest update (0.8.7.2) has the colors functions working correctly now like they did before.

Going forward, we will only use this include as all games use the same general color codes and it is general enough to be used in multiple games from various Source engine versions without worry of compatibility issues. Thank you for the report. Closing issue.
