### ISSUE TITLE
Doubt with SMAC Version | CSGO

### ISSUE THREAD

**Issue by paulocrash** [Silenci0/SMAC#4]
First of all congratulations for updating the plugin, I just have to thank you.

What would you like to know if your version supports CSGO or just FT2? If in your version you also corrected the BUG of the CSGO where it was applying banishes in all players by AimBot even without the player does not nothing to you, just of connecting in the server it already took ban.

Thanks again for the fix of the plugin so far and hope you continue with this work.

_**OBS: If this plugin is functional for CSGO I do not see problem in making a donation as a simple form of thanks to you, if you allow, just let me know some link.**_

**Comment by Silenci0** [comment]
My version has been tested in TF2 and ZPS 3.0 and should be compatible with most other source games that it supported before. However, I have not tested anything for CS:GO since I don't play the game or run servers for it, so I cannot guarantee that is works 100%. I have, however, kept the plugin up-to-date with the latest Sourcemod changes, some updates for some games, and general code clean up.

Currently, the eyetest module does not work for CS:GO. Part of the problem with eyetest is alt-tabbing that causes issues which triggers the module, which also happens to be the same issue in TF2 from what I've heard. I'm looking into fixing that, but progress in general is rather slow due to personal commitments IRL. As far as the aimbot module, I haven't heard that it was broken for CS:GO, but if it is, you may wish to set smac_aimbot_ban to 0 before using it just in case.

As far as donations, I don't plan on accepting any, but thank you for the thought.

**Comment by Silenci0** [comment]
I will be closing this issue. I will check the potential aimbot problem in CS:GO (assuming it exists for this version of SMAC) if/when I have time.

**Comment by paulocrash** [comment]
Sorry for the delay to answer, problems on the way ...

Anyway, I understand your position, in any case thank you!
