### ISSUE TITLE
smac commands kick

### ISSUE THREAD

**Issue by Ayrton09** [Silenci0/SMAC#8]
hello silenci0, i tested your latest version on csgo (sourcemod 1.9 latest) everythings works fine but seems like smac_commands.smx is kicking everyone without reason.

**Comment by Silenci0** [comment]
Hello Ayrton,

Is it CS:GO that the plugins are being used for or is it another game? Also, do you happen to know what commands might be kicking people or if there are any logs for SMAC on the server that indicate the command module is kicking players? If there are logs, please post them for me (you may want to redact player names and IP info prior to posting) as it can potentially help me narrow down the issue.

Thanks,

Silence

**Comment by Ayrton09** [comment]
hello, yep its only on csgo, never had this problem before with "smac.commands.smx" since i updated to the new version I had to remove it.
the only log i got is "kicked for spamming" and no one can join.

recently i tried the plugin on a clean server i didnt get kicked, seems like some plugins are causing the issue with the new version. i will give you more information while im investigating 

[SM] Listing 74 plugins:
  01 "[CSS/CS:GO] AbNeR ResetScore" (1.5fix) by AbNeR_CSS
  02 "Admin File Reader" (1.9.0.6281) by AlliedModders LLC
  03 "Admin Help" (1.9.0.6281) by AlliedModders LLC
  04 "Admin List" (1.2) by Fredd
  05 "Admin Menu" (1.9.0.6281) by AlliedModders LLC
  06 "Advertisements" (2.0.2) by Tsunami
  07 "Anti-Flood" (1.9.0.6281) by AlliedModders LLC
  08 "arms.smx"
  09 "Basic Ban Commands" (1.9.0.6281) by AlliedModders LLC
  10 "Basic Chat" (1.9.0.6281) by AlliedModders LLC
  11 "Basic Comm Control" (1.9.0.6281) by AlliedModders LLC
  12 "Basic Commands" (1.9.0.6281) by AlliedModders LLC
  13 "Basic Info Triggers" (1.9.0.6281) by AlliedModders LLC
  14 "Basic Votes" (1.9.0.6281) by AlliedModders LLC
  15 "Connect Announce" (1.8) by Arg!
  16 "Client Preferences" (1.9.0.6281) by AlliedModders LLC
  17 "[CS:GO] bug fix - bot add jointeam" (1.0) by Bacardi
  18 "[CSGO] Team Limit Bypass" (1.1) by Zephyrus
  19 "Ent-Control" (0.0.1.81) by LeGone
  20 "SM ExoJump Boots Giver" (1.0.3) by Franc1sco franug
  21 "Force AllTalk" (1.1) by Nickelony
  22 "Fun Commands" (1.9.0.6281) by AlliedModders LLC
  23 "Fun Votes" (1.9.0.6281) by AlliedModders LLC
  24 "Give Weapon" (1.0) by Kiske
  25 "[ANY] Ban Disconnected Player" (2.0) by Headline, Original Plugin : mad_hamster
  26 "High Ping Kicker - Lite Edition" (1.0.0.1) by Liam
  27 "[CS:GO] Damage Text" (1.6) by Kento, Kxnrl, IT-KiLLER, root88
  28 "[CS:GO] Custom Radio Sound" (1.1.3) by Kento
  29 "Map configs" (1.3) by Berni
  30 "Map end cvars reset" (2.1) by St00ne
  31 "Noblock for players and nades" (1.0) by tommie113
  32 "Only Headshot" (2.0.2) by Bara
  33 "PermaMute" (0.1) by Ryan "FLOOR_MASTER" Mannion (Editors: R1KO and XERXES AT)
  34 "PickAll" (1.0) by Hexah
  35 "Player Commands" (1.9.0.6281) by AlliedModders LLC
  36 "Radio Spam Block" (1.0.1csgofix) by exvel,TonyBaretta
  37 "Reserved Slots" (1.9.0.6281) by AlliedModders LLC
  38 "Player Respawn" (1.6) by Rogue
  39 "Self-Mute Intelligence" (1.5.2) by IT-KiLLER and (Otokiru, edit 93x, Accelerator)
  40 "SourceMod Anti-Cheat" (0.8.6.4) by SMAC Development Team (original), Mr. Silence (updated)
  41 "SMAC Aimbot Detector" (0.8.6.4) by SMAC Development Team (original), Mr. Silence (updated)
  42 "SMAC AutoTrigger Detector" (0.8.6.4) by SMAC Development Team (original), Mr. Silence (updated)
  43 "SMAC Client Protection" (0.8.6.4) by SMAC Development Team (original), Mr. Silence (updated)
  44 "SMAC ConVar Checker" (0.8.6.4) by SMAC Development Team (original), Mr. Silence (updated)
  45 "SMAC Rcon Locker" (0.8.6.4) by SMAC Development Team (original), Mr. Silence (updated)
  46 "SM Advanced Teleport" (1.0) by LightningZLaser
  47 "SM File/Folder Downloader and Precacher" (1.4) by SWAT_88
  48 "Soccer Mod" (2019.5.6) by Marco Boogers (updated by Ayrton09)
  49 "Sound Commands" (1.9.0.6281) by AlliedModders LLC
  50 "Teamswitch Menu" (0.2.6) by R-Hehl
  51 "Toggle Music" (3.7.8) by Mitch & Agent Wesker
  52 "Toggle Weapon Sounds clientprefs" (1.0.3 fix m_iWeaponID + new syntax) by GoD-Tony
  53 "[UMC] Admin Menu" (3.6.2) by Steell
  54 "[UMC] Ultimate Mapchooser Core" (3.6.2) by Original:Steell, Updates:Powerlord (3.4.6-dev), Mr.Silence (3.6.2)
  55 "[UMC] Echo Nextmap" (3.6.2) by Steell
  56 "[UMC] End of Map Vote Warnings" (3.6.2) by Steell
  57 "[UMC] End of Map Vote" (3.6.2) by Steell
  58 "[UMC] Nominations" (3.6.2) by Steell
  59 "[UMC] Player Limits" (3.6.2) by Steell
  60 "[UMC] Post-Played Exclusion" (3.6.2) by Sazpaimon and Steell
  61 "[UMC] Rock The Vote" (3.6.2) by Steell
  62 "[UMC] Time Limits" (3.6.2) by Steell
  63 "[UMC] Vote Command" (3.6.2) by Steell
  64 "VoiceAnnounceEx" (2.2.0) by Franc1sco franug, Mini and GoD-Tony
  65 "Weapon Restrict" (4.0.0-b7) by Dr!fter
  66 "Coinflip" (1.2) by hAlexr
  67 "[STORE] MineSweeper" (1.0) by hAlexr
  68 "CS:GO Movement Unlocker" (1.0) by Peace-Maker
  69 "Store - Trade System" (1.0) by Zephyrus
  70 "Store - The Resurrection" (1.1) by Zephyrus
  71 "Thirdperson | Mirrow Mode" (1.11) by Zephyrus
  72 "AFK Manager" (4.3.0) by Rothgar
 
  73 "RankMe" (3.0.3.Kento.31.2) by lok1, Scooby, Kento, pracc, Kxnrl, CrazyHackGUT
  74 "Game_Player_Equip Fix" (1.1.1) by Mitch

**Comment by Silenci0** [comment]
Hi Aryton,

Looking into it from the code end, what is getting activated is the command spam portions of the code, which the cvar **smac_antispam_cmds** controls. By default, it is set to 20 commands per second, so whatever is triggering this is causing is spamming a particular command 20 times. 

If you set **smac_antispam_cmds** to 0 in your smac.cfg file, it should disable the check for command spam. As a test, try to disable it without disabling the plugin and see if you keep getting kicked for command spam. 

On another note, I have not updated the code for this module in some time, though I have recompiled the plugin during every update so that it keeps up with the changes in both the includes and the core module, so not much has changed in the module itself. However, since it is kicking people, it should be logging the command (as well as client info) in the "SMAC.log" file in "addons/sourcemod/logs". If that log isn't present, please try to create a log file in that folder named "SMAC.log" and re-enable the plugin's anti-spam feature. If the code is logging everything correctly, it should show the actual command that people are being kicked for.

**Comment by Ayrton09** [comment]
hello, i installed smac commands again to show you the logs here is what i got
[smac_commands.smx | 0.8.6.4] ⭐Ayrton09⭐💗 (ID: STEAM_1:1:37229756 | IP: ) was kicked for spamming: snd_setsoundparam Music.WonRound.valve_csgo_02 volume 0

**Comment by Silenci0** [comment]
Thank you for the update!

It looks like snd_setsoundparam is a CS:GO command for adjusting sound parameters and, for whatever reason, it is being spammed somehow. Looking into this further, there was an update on 05/29/2019 regarding this command and it has been removed from CS:GO, so it shouldn't even be an issue. However, for whatever reason, the command is being triggered, so it might possibly be a bug of some sort that came out with a recent release. 

Regardless of the reason, it is still causing SMAC to trigger the anti-spam commands. If there is some kind of bind or autoexec.cfg file with this command in it, it may be a good idea to remove it and any instances of it from your client configs. If that isn't the case, then its definitely a client-side thing that is not working correctly. This is definitely a false positive of some sort, so you may want to either: 

1. set **smac_antispam_cmds** to 0 to disable the spam check or
2. remove the commands module completely.

This is a temporary solution for now until I can update the commands plugin to ignore this particular command. I will also be adding a cvar to set the module to give the choice to simply notify when someone is spamming commands rather than kicking them just in case people would rather have that than simply having an autokick upon command spam. 

Thank you again for the report, I will hopefully be able to update the plugins within this week/weekend and release an updated version. I will respond back to this issue once it has been updated.

**Comment by Ayrton09** [comment]
thanks! for your work! <3

**Comment by Silenci0** [comment]
Plugin has been updated to 0.8.6.5 with snd_setsoundparam added as a command to be ignored when used (so it does not count as spam when the plugin checks) and the new smac_anticmdspam_kick feature that I mentioned was added and tested in TF2 (since I have a test server setup for testing general purpose stuff). 

This issue should be resolved, but feel free to let me know if its not working. Alternatively, you can block this command yourself with the plugins various commands that can add/ignore or remove a command to be listened for/checked for (as stated earlier in this issue). Thanks again for reporting the issue.
