### ISSUE TITLE
SMAC RCon crash

### ISSUE THREAD

**Issue by MAGNAT2645** [Silenci0/SMAC#9]
SMAC RCon module seems to cause server crash when i'm trying to execute commands via RCon.
Crash related to SM RCon and only SMAC RCon uses it.
This started to happen after installing SourceMod 1.10.

More information is [here](https://forums.alliedmods.net/showpost.php?p=2663707&postcount=203).
At this moment i can't test it without SM Rcon because it happens on public server with players and RCon ([Source Admin Tool](https://forums.alliedmods.net/showthread.php?t=289370)) doesn't work (doesn't execute any commands) on my test server.

P.S. Public server on Ubuntu and test server on Windows.

**Comment by Silenci0** [comment]
The smac_rcon plugin should detect if the SM RCon library is installed or not and it will only run functions that utilizes SM RCon if it finds the library, so it should be possible to disable the extension and reload the plugin to fix the potential crashes. When it is possible, disable/remove the SM RCon extension and reload the smac_rcon plugin and see if it still gives you problems. This will mean that the IP whitelisting feature will no longer work. 

If SM Rcon is no longer being supported, I will remove/disable the functionality from SMAC. Alternatively, have you tried using sm_rcon instead of server rcon to run commands or does the same thing occur?

**Comment by Silenci0** [comment]
I just did a test on my windows test server without the SM RCon extension available while running smac_rcon and running RCon commands without it did not crash the server. It should be disabled if the library is removed/disabled and the smac_rcon plugin is reloaded. My test server is currently using SM 1.9

Also, as an fyi, I only develop SMAC (and other plugins I maintain) on the stable branches of sourcemod (which is currently 1.9) and not the dev builds as most people will be using the stable builds unless circumstances require otherwise. In most cases, the dev builds will be compatible with plugins compiled on earlier versions of Sourcemod (unless there are significant changes being made to the dev branch that would break plugin compatibility, which generally doesn't happen), so working with the stable build is the safer bet compatibility wise.

Anyway, remove SM RCon's extension from your server and let me know if any further problems come up as a result of smac_rcon being used on SM 1.10 as I will make a note of it for later when I need to update the plugins for the latest version of SM.

**Comment by MAGNAT2645** [comment]
I don't know why, but many people advise to switch to SM 1.10, even Asherkin (at least to improve Accelerator functionality).

I will try use sm_rcon instead (but in this case i can't use Source Admin Tool) and will test rcon without SMRcon extension.

**Comment by Silenci0** [comment]
Alright, got it. If people are suggesting to others to use SM 1.10, then I'll take a look at those changes to see if SMAC is still compatible with that build. I think SMAC should be since it only seems like the extension is the problem, but I'll double-check everything just in case. 

Still, I think it might just be the extension that is not working, so removing SMRCon and reloading SMAC will probably fix the crashes and allow you to use normal Rcon again. However, if that is not the case and it is still causing issues, I will release a hotfix temporarily removing all code associated to SMRCon in the smac_rcon plugin until the issue is resolved.

**Comment by MAGNAT2645** [comment]
So, i removed extension and now RCon doesn't crash server.

**Comment by Silenci0** [comment]
Alright, thank you for the report, it is appreciated. 

I will be keeping an eye on the SM RCon extension to see if it will eventually get an update as it seems the changes made to SM 1.10 might have broken the extension (there is the possibility that it needs a gamedata update as well). If it gets no further updates, I may need to remove the SM RCon functions from the smac_rcon plugin or I may look into what the extension needs to work correctly and see about fixing it. 

In either case, I will be making a note that SM RCon extension does not seem to work correctly at this time. Thank you again for the report.
